### ISSUE TITLE
Implementations for abstract classes

### ISSUE THREAD

**Issue by mikera** [adereth/apache-commons-matrix#1]
Great job on the new core.matrix implementation!

One quick thought: it may be better to extend the protocols to the Apache Commons abstract base classes in many cases, rather than the concrete implementation classes.

For example, in many cases it is possible to extend the protocol to `RealVector` instead of `ArrayRealVector`

Advantage of this approach is that it will allow different apache vector classes (e.g. `SparseRealVector`) or new implementation created by others to benefit from the same protocol extension.

**Comment by adereth** [comment]
Yes, totally should have done that in the first place.  My initial thinking was that some of the implementations have limited functionality, like [DiagonalMatrix](http://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math3/linear/DiagonalMatrix.html) throwing exceptions when setting off-diagonal values.  I'm now convinced that's not my problem.

**Comment by mikera** [comment]
Arguably setting off-diagonal values on a diagonal matrix is a bit of an unusual operation anyway, so it's fine for it to be a bit trickier to make that work :-) I actually updated the core.matrix docstrings to suggest using `(mutable (diagonal-matrix ....))` for this case
